name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ioannapapanikolaou/mlflow-docker-example:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ioannapapanikolaou/mlflow-docker-example:latest

  run:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull ioannapapanikolaou/mlflow-docker-example:latest

      - name: Run Docker container
        run: docker run --rm ioannapapanikolaou/mlflow-docker-example:latest

